export const expressionLabels: Record<string, string> = {
  admiration: "Admiration",
  adoration: "Adoration",
  aestheticAppreciation: "Aesthetic Appreciation",
  amusement: "Amusement",
  anger: "Anger",
  annoyance: "Annoyance",
  anxiety: "Anxiety",
  awe: "Awe",
  awkwardness: "Awkwardness",
  boredom: "Boredom",
  calmness: "Calmness",
  concentration: "Concentration",
  contemplation: "Contemplation",
  confusion: "Confusion",
  contempt: "Contempt",
  contentment: "Contentment",
  craving: "Craving",
  determination: "Determination",
  disappointment: "Disappointment",
  disapproval: "Disapproval",
  disgust: "Disgust",
  distress: "Distress",
  doubt: "Doubt",
  ecstasy: "Ecstasy",
  embarrassment: "Embarrassment",
  empathicPain: "Empathic Pain",
  enthusiasm: "Enthusiasm",
  entrancement: "Entrancement",
  envy: "Envy",
  excitement: "Excitement",
  fear: "Fear",
  gratitude: "Gratitude",
  guilt: "Guilt",
  horror: "Horror",
  interest: "Interest",
  joy: "Joy",
  love: "Love",
  neutral: "Neutral",
  nostalgia: "Nostalgia",
  pain: "Pain",
  pride: "Pride",
  realization: "Realization",
  relief: "Relief",
  romance: "Romance",
  sadness: "Sadness",
  sarcasm: "Sarcasm",
  satisfaction: "Satisfaction",
  shame: "Shame",
  surprise: "Surprise",
  surpriseNegative: "Surprise (Negative)",
  surprisePositive: "Surprise (Positive)",
  sympathy: "Sympathy",
  tiredness: "Tiredness",
  triumph: "Triumph",
};

export const expressionEmojis: Record<string, string> = {
  admiration: "🤩",
  adoration: "😍",
  aestheticAppreciation: "🎨",
  amusement: "😄",
  anger: "😠",
  annoyance: "😒",
  anxiety: "😰",
  awe: "😲",
  awkwardness: "😳",
  boredom: "😴",
  calmness: "😌",
  concentration: "🧐",
  contemplation: "🤔",
  confusion: "😕",
  contempt: "😤",
  contentment: "☺️",
  craving: "🤤",
  determination: "😤",
  disappointment: "😞",
  disapproval: "👎",
  disgust: "🤢",
  distress: "😫",
  doubt: "🤨",
  ecstasy: "🤯",
  embarrassment: "😳",
  empathicPain: "😢",
  enthusiasm: "🙌",
  entrancement: "😵",
  envy: "😒",
  excitement: "🤩",
  fear: "😨",
  gratitude: "🙏",
  guilt: "😣",
  horror: "😱",
  interest: "🤔",
  joy: "😃",
  love: "❤️",
  neutral: "😐",
  nostalgia: "🥲",
  pain: "😖",
  pride: "😊",
  realization: "💡",
  relief: "😅",
  romance: "💕",
  sadness: "😢",
  sarcasm: "😏",
  satisfaction: "😌",
  shame: "🫣",
  surprise: "😮",
  surpriseNegative: "😮",
  surprisePositive: "😲",
  sympathy: "🤗",
  tiredness: "😪",
  triumph: "🏆",
};

export const categorizedExpressions: Record<string, string[]> = {
  positive: [
    "Admiration",
    "Adoration",
    "Aesthetic Appreciation",
    "Amusement",
    "Awe",
    "Contentment",
    "Ecstasy",
    "Enthusiasm",
    "Excitement",
    "Joy",
  ],
  negative: [
    "Anger",
    "Annoyance",
    "Anxiety",
    "Contempt",
    "Disappointment",
    "Disapproval",
    "Disgust",
    "Distress",
    "Fear",
    "Sadness",
  ],
  neutral: [
    "Calmness",
    "Concentration",
    "Contemplation",
    "Confusion",
    "Doubt",
    "Neutral",
    "Sarcasm",
    "Surprise",
    "Surprise (Positive)",
    "Surprise (Negative)",
  ],
  motivation: [
    "Determination",
    "Craving",
    "Curiosity",
    "Entrancement",
    "Realization",
    "Relief",
    "Satisfaction",
    "Triumph",
    "Pride",
    "Nostalgia",
  ],
  complexSocial: [
    "Sympathy",
    "Gratitude",
    "Empathic Pain",
    "Envy",
    "Romance",
    "Love",
    "Embarrassment",
    "Shame",
    "Guilt",
    "Pain",
  ],
  reflective: [
    "Awkwardness",
    "Boredom",
    "Horror",
    "Tiredness",
    "Embarrassment",
    "Sarcasm",
    "Interest",
    "Realization",
    "Disgust",
    "Contemplation",
  ],
};
